version: '3.8'

services:
  postgres:
    build:
      context: ./api/postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    depends_on:
      - postgres

  server:
    build: ./api/api-server
    depends_on:
      - postgres
    ports:
      - 5005:5005
    restart: always

  app:
    build: ./app
    depends_on:
      - server
    ports:
      - 3000:3000
