version: '3.8'

services:
  postgres:
    build: ./api/postgres
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  server:
    build: ./api/api-server
    container_name: backend
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 5005:5005
    restart: always

  app:
    build: ./app
    container_name: frontend
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:5005/api
    ports:
      - 3000:3000
